package web

import (
	"context"
	"net/http"
	"strings"

	"scriptboard/internal/identity"
)

func (a *App) routes() http.Handler {
	mux := newDeclaredRouteMux()
	mux.Public("GET /assets/app-v2.css", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/css; charset=utf-8", appCSS)
	})
	mux.Public("GET /assets/app.css", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/css; charset=utf-8", appCSS)
	})
	mux.Public("GET /assets/app-v2.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", appJS)
	})
	mux.Public("GET /assets/markdown-it.min.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", markdownItJS)
	})
	mux.Public("GET /assets/purify.min.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", domPurifyJS)
	})
	mux.Public("GET /assets/highlight.min.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", highlightJS)
	})
	mux.Public("GET /assets/highlight-powershell.min.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", highlightPowerShellJS)
	})
	mux.Public("GET /assets/highlight-dos.min.js", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "text/javascript; charset=utf-8", highlightDOSJS)
	})
	mux.Public("GET /favicon.ico", func(response http.ResponseWriter, request *http.Request) {
		serveWebAsset(response, request, "image/x-icon", scriptboardFaviconICO)
	})
	mux.Handle("GET /{$}", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		http.Redirect(response, request, "/monitor", http.StatusSeeOther)
	})))
	mux.Public("GET /login", func(response http.ResponseWriter, request *http.Request) {
		if _, _, ok := a.loadSession(request); ok {
			http.Redirect(response, request, "/monitor", http.StatusSeeOther)
			return
		}
		renderLoginPage(response, request, http.StatusOK, "", "")
	})
	mux.Public("POST /login", a.login)
	mux.Public("GET /login/verify", a.loginVerificationPage)
	mux.Public("POST /login/verify", a.verifyLoginFactor)
	mux.Public("POST /auth/passkey/options", a.beginPasskeyLogin)
	mux.Public("POST /settings/locale", a.setWebLocale)
	mux.External("POST /trigger", a.externalTrigger)
	mux.External("POST /trigger/{name}", a.externalTrigger)
	mux.External("POST /trigger/{group}/{name}", a.externalTrigger)
	mux.External("GET /api/fleet/v1/status", a.fleetStatusExport)
	mux.Handle("GET /auth/step-up", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.stepUpTask)))
	mux.Handle("POST /auth/step-up", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.stepUp)))
	mux.Handle("POST /auth/passkey/step-up/options", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.beginPasskeyStepUp)))
	mux.Handle("POST /logout", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.logout)))
	mux.Handle("GET /monitor", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.overviewPage)))
	mux.Handle("GET /monitor/nodes/new", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.newFleetNodeTask)))
	mux.Handle("GET /monitor/nodes/{id}/edit", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.editFleetNodeTask)))
	mux.Handle("POST /monitor/nodes", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createFleetNode)))
	mux.Handle("POST /monitor/nodes/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateFleetNode)))
	mux.Handle("POST /monitor/nodes/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteFleetNode)))
	mux.Handle("GET /monitor/security", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.securityPage)))
	mux.Handle("POST /monitor/security/baseline/snapshot", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.captureSecurityBaseline)))
	mux.Handle("POST /monitor/security/components/{component}/install", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.installSecurityComponent)))
	mux.Handle("POST /monitor/security/fail2ban/unban", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.unbanSecurityIP)))
	mux.Handle("GET /monitor/security/fail2ban/ban", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.newFail2BanBanTask)))
	mux.Handle("POST /monitor/security/fail2ban/ban", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.banSecurityIP)))
	mux.Handle("POST /monitor/security/firewall/draft/rules", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.addSecurityFirewallDraftRule)))
	mux.Handle("GET /monitor/security/firewall/rules/new", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.newLinuxFirewallRuleTask)))
	mux.Handle("GET /monitor/security/firewall/review", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.reviewSecurityFirewallTask)))
	mux.Handle("POST /monitor/security/firewall/draft/defaults", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.updateSecurityFirewallDraftDefaults)))
	mux.Handle("POST /monitor/security/firewall/draft/toggle", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.toggleSecurityFirewallDraftRule)))
	mux.Handle("POST /monitor/security/firewall/draft/delete", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.deleteSecurityFirewallDraftRule)))
	mux.Handle("POST /monitor/security/firewall/draft/discard", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.discardSecurityFirewallDraft)))
	mux.Handle("POST /monitor/security/firewall/draft/apply", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.applySecurityFirewallDraft)))
	mux.Handle("POST /monitor/security/firewall/enable", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.enableSecurityFirewall)))
	mux.Handle("GET /monitor/security/windows-firewall/rules/new", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.newWindowsFirewallRuleTask)))
	mux.Handle("POST /monitor/security/windows-firewall/rules", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.addWindowsFirewallRule)))
	mux.Handle("POST /monitor/security/windows-firewall/toggle", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.toggleWindowsFirewallRule)))
	mux.Handle("POST /monitor/security/windows-firewall/delete", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.deleteWindowsFirewallRule)))
	mux.Handle("GET /monitor/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.overviewData)))
	mux.Handle("GET /monitor/status", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.shellStatus)))
	mux.Handle("GET /monitor/applications", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationsPage)))
	mux.Handle("GET /monitor/applications/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationsData)))
	mux.Handle("GET /monitor/applications/{id}/logs", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationLogPage)))
	mux.Handle("GET /monitor/applications/{id}/logs/download", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationLogDownload)))
	mux.Handle("GET /monitor/applications/{id}/logs/history", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationLogHistory)))
	mux.Handle("GET /monitor/applications/{id}/logs/events", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationLogEvents)))
	mux.Handle("GET /monitor/applications/{id}/details", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.applicationDetails)))
	mux.Handle("POST /monitor/applications/{id}/pin", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.pinApplication)))
	mux.Handle("POST /monitor/applications/{id}/unpin", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.unpinApplication)))
	mux.Handle("POST /monitor/applications/{id}/move", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.movePinnedApplication)))
	mux.Handle("GET /monitor/containers", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.containersPage)))
	mux.Handle("GET /monitor/containers/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.containersData)))
	mux.Handle("GET /monitor/containers/{name}/details", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.containerDetails)))
	mux.Handle("POST /monitor/containers/{name}/pin", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.pinContainer)))
	mux.Handle("POST /monitor/containers/{name}/unpin", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.unpinContainer)))
	mux.Handle("POST /monitor/containers/{name}/move", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.movePinnedContainer)))
	mux.Handle("POST /monitor/containers/{name}/operate", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.operateContainer)))
	mux.Handle("GET /monitor/kubernetes", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.kubernetesPage)))
	mux.Handle("GET /monitor/kubernetes/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.kubernetesData)))
	mux.Handle("GET /monitor/kubernetes/connections/new", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.kubernetesConnectionTask)))
	mux.Handle("POST /monitor/kubernetes/connections", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.saveKubernetesConnection)))
	mux.Handle("POST /monitor/kubernetes/connections/test", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.testKubernetesConnection)))
	mux.Handle("GET /monitor/kubernetes/connections/{connection}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.kubernetesConnectionTask)))
	mux.Handle("POST /monitor/kubernetes/connections/{connection}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.saveKubernetesConnection)))
	mux.Handle("POST /monitor/kubernetes/connections/{connection}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteKubernetesConnection)))
	mux.Handle("GET /monitor/kubernetes/local/download", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.downloadLocalKubeconfig)))
	mux.Handle("GET /monitor/kubernetes/local/contexts/{context}/download", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.downloadLocalKubeconfigContext)))
	mux.Handle("POST /monitor/kubernetes/local/import/preview", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.previewLocalKubeconfigImport)))
	mux.Handle("POST /monitor/kubernetes/local/import", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.importLocalKubeconfig)))
	mux.Handle("POST /monitor/kubernetes/local/contexts", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.mutateLocalKubeconfigContext)))
	mux.Handle("POST /monitor/kubernetes/local/contexts/{context}/connection", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.addLocalKubeconfigConnection)))
	mux.Handle("POST /monitor/kubernetes/local/contexts/{context}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.mutateLocalKubeconfigContext)))
	mux.Handle("GET /monitor/kubernetes/clusters/{connection}/workloads/{namespace}/{kind}/{name}/details", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.kubernetesWorkloadDetails)))
	mux.Handle("GET /monitor/kubernetes/clusters/{connection}/workloads/{namespace}/{kind}/{name}/logs", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.kubernetesWorkloadLogs)))
	mux.Handle("GET /monitor/kubernetes/clusters/{connection}/workloads/{namespace}/{kind}/{name}/logs/download", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.downloadKubernetesWorkloadLogs)))
	mux.Handle("POST /monitor/kubernetes/clusters/{connection}/workloads/{namespace}/{kind}/{name}/operate", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.operateKubernetesWorkload)))
	mux.Handle("GET /monitor/websites", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.websiteMonitorList)))
	mux.Handle("GET /config/dashboards", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.customDashboardPage)))
	mux.Handle("POST /config/dashboards", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createCustomDashboard)))
	mux.Handle("POST /config/dashboards/import", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.importCustomDashboard)))
	mux.Handle("POST /config/dashboards/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateCustomDashboard)))
	mux.Handle("GET /config/dashboards/{id}/export", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.exportCustomDashboard)))
	mux.Handle("POST /config/dashboards/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteCustomDashboard)))
	mux.Handle("POST /config/dashboards/{id}/refresh", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.refreshCustomDashboard)))
	mux.Handle("POST /config/dashboards/{id}/cards", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-card-tests", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.testCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-cards/{id}/test", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.testCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-cards/{id}/refresh", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.refreshCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-cards/{id}/registry/insecure", a.requireStepUp(identity.PermissionConfigureDockerEngine, http.HandlerFunc(a.registerCustomDashboardInsecureRegistry)))
	mux.Handle("POST /config/dashboard-cards/{id}/move", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.moveCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-cards/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateCustomDashboardCard)))
	mux.Handle("POST /config/dashboard-cards/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteCustomDashboardCard)))
	mux.Handle("GET /monitor/dashboards", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.legacyCustomDashboardPage)))
	mux.Handle("GET /monitor/dashboard/{id}", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.customDashboardMonitorPage)))
	mux.Handle("POST /monitor/dashboards", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createCustomDashboard)))
	mux.Handle("POST /monitor/dashboards/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateCustomDashboard)))
	mux.Handle("POST /monitor/dashboards/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteCustomDashboard)))
	mux.Handle("POST /monitor/dashboards/{id}/cards", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createCustomDashboardCard)))
	mux.Handle("POST /monitor/dashboard-cards/{id}/refresh", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.refreshCustomDashboardCard)))
	mux.Handle("POST /monitor/dashboard-cards/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateCustomDashboardCard)))
	mux.Handle("POST /monitor/dashboard-cards/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteCustomDashboardCard)))
	mux.Public("GET /public/dashboard/{slug}", a.publicCustomDashboard)
	mux.Handle("GET /monitor/websites/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.websiteMonitorData)))
	mux.Handle("GET /monitor/websites/new", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.websiteMonitorCreateTask)))
	mux.Handle("POST /monitor/websites", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.createWebsiteMonitor)))
	mux.Handle("POST /monitor/websites/reorder", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.reorderWebsiteMonitors)))
	mux.Handle("GET /monitor/websites/export", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.websiteMonitorExportTask)))
	mux.Handle("POST /monitor/websites/export", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.exportWebsiteMonitors)))
	mux.Handle("GET /monitor/websites/import", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.websiteMonitorImportTask)))
	mux.Handle("POST /monitor/websites/import/preview", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.previewWebsiteMonitorImport)))
	mux.Handle("POST /monitor/websites/import", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.importWebsiteMonitors)))
	mux.Handle("GET /monitor/websites/nginx", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.websiteMonitorNginxTask)))
	mux.Handle("POST /monitor/websites/nginx/scan", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.scanWebsiteMonitorNginx)))
	mux.Handle("POST /monitor/websites/nginx/import", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.importWebsiteMonitorNginx)))
	mux.Handle("GET /monitor/websites/{id}/edit", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.websiteMonitorEditTask)))
	mux.Handle("POST /monitor/websites/{id}", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.updateWebsiteMonitor)))
	mux.Handle("GET /monitor/websites/{id}", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.websiteMonitorDetail)))
	mux.Handle("GET /monitor/websites/{id}/data", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.websiteMonitorDetailData)))
	mux.Handle("POST /monitor/websites/{id}/check", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.checkWebsiteMonitorNow)))
	mux.Handle("POST /monitor/websites/{id}/pause", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.pauseWebsiteMonitor)))
	mux.Handle("POST /monitor/websites/{id}/resume", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.resumeWebsiteMonitor)))
	mux.Handle("POST /monitor/websites/{id}/move", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.moveWebsiteMonitor)))
	mux.Handle("POST /monitor/websites/{id}/delete", a.requirePermission(identity.PermissionManageOperations, http.HandlerFunc(a.deleteWebsiteMonitor)))
	mux.Handle("GET /settings/account", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		current := request.Context().Value(sessionContextKey).(session)
		mfaStatus, err := a.mfa.Status(current.userID)
		if err != nil {
			http.Error(response, webText(resolveWebLocale(request), "mfa.unavailable"), http.StatusInternalServerError)
			return
		}
		passkeyUser, err := a.passkeys.User(current.userID, current.username)
		if err != nil {
			http.Error(response, webText(resolveWebLocale(request), "mfa.unavailable"), http.StatusInternalServerError)
			return
		}
		response.Header().Set("Content-Type", "text/html; charset=utf-8")
		_ = accountTemplate.Execute(response, struct {
			Username, CSRFToken string
			CredentialOverride  bool
			CanRename           bool
			MFAEnabled          bool
			Locale              webLocale
			SettingsNavigation  settingsNavigationData
		}{
			Username: current.username, CSRFToken: current.csrfToken,
			CredentialOverride: a.credentialOverride && current.role == identity.RoleAdministrator,
			CanRename:          current.role == identity.RoleAdministrator, MFAEnabled: mfaStatus.Enabled || len(passkeyUser.Credentials) > 0, Locale: resolveWebLocale(request),
			SettingsNavigation: newSettingsNavigation(current, resolveWebLocale(request), "account"),
		})
	})))
	mux.Handle("POST /settings/account", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.changePassword)))
	mux.Handle("GET /settings/account/username", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.accountUsernameTask)))
	mux.Handle("POST /settings/account/username", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.changeUsername)))
	mux.Handle("GET /settings/account/password", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.accountPasswordTask)))
	mux.Handle("POST /settings/account/password", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.changePassword)))
	mux.Handle("GET /settings/account/mfa", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.accountMFAPage)))
	mux.Handle("POST /settings/account/mfa/enroll", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.beginMFAEnrollment)))
	mux.Handle("POST /settings/account/mfa/confirm", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.confirmMFAEnrollment)))
	mux.Handle("POST /settings/account/mfa/reset", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.resetMFA)))
	mux.Handle("POST /settings/account/passkeys/register/options", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.beginPasskeyRegistration)))
	mux.Handle("POST /settings/account/passkeys/register/finish", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.finishPasskeyRegistration)))
	mux.Handle("POST /settings/account/passkeys/{id}/delete", a.requireStepUp(identity.PermissionObserve, http.HandlerFunc(a.deletePasskey)))
	mux.Handle("GET /settings/users", a.requirePermission(identity.PermissionManageUsers, http.HandlerFunc(a.usersPage)))
	mux.Handle("GET /settings/users/create", a.requirePermission(identity.PermissionManageUsers, http.HandlerFunc(a.createUserTask)))
	mux.Handle("POST /settings/users", a.requireStepUp(identity.PermissionManageUsers, http.HandlerFunc(a.createUser)))
	mux.Handle("GET /settings/users/{id}/edit", a.requirePermission(identity.PermissionManageUsers, http.HandlerFunc(a.editUserTask)))
	mux.Handle("POST /settings/users/{id}/disable", a.requireStepUp(identity.PermissionManageUsers, http.HandlerFunc(a.disableUser)))
	mux.Handle("POST /settings/users/{id}/enable", a.requireStepUp(identity.PermissionManageUsers, http.HandlerFunc(a.enableUser)))
	mux.Handle("POST /settings/users/{id}/update", a.requireStepUp(identity.PermissionManageUsers, http.HandlerFunc(a.updateUser)))
	mux.Handle("POST /settings/users/{id}/reset-password", a.requireStepUp(identity.PermissionManageUsers, http.HandlerFunc(a.resetUserPassword)))
	mux.Handle("GET /settings/name", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.instanceNameSettingsPage)))
	mux.Handle("POST /settings/name", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.updateInstanceName)))
	mux.Handle("GET /settings/nodes", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.fleetNodeSettingsPage)))
	mux.Handle("GET /settings/nodes/access-tokens/new", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.newFleetAccessTokenTask)))
	mux.Handle("POST /settings/nodes/access-tokens", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.createFleetAccessToken)))
	mux.Handle("POST /settings/nodes/access-tokens/{id}/delete", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.revokeFleetAccessToken)))
	mux.Handle("GET /settings/display", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		current := request.Context().Value(sessionContextKey).(session)
		locale := resolveWebLocale(request)
		response.Header().Set("Content-Type", "text/html; charset=utf-8")
		_ = displaySettingsTemplate.Execute(response, struct {
			Locale             webLocale
			SettingsNavigation settingsNavigationData
		}{Locale: locale, SettingsNavigation: newSettingsNavigation(current, locale, "display")})
	})))
	mux.Handle("GET /settings/updates", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.updatesPage)))
	mux.Handle("GET /settings/service-logs", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(redirectLegacyServiceLogs)))
	mux.Handle("GET /settings/service-logs/export", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(redirectLegacyServiceLogsExport)))
	mux.Handle("GET /settings/notifications", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.notificationsPage)))
	mux.Handle("GET /settings/state-backups", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.stateBackupsPage)))
	mux.Handle("POST /settings/state-backups/create", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.createStateBackup)))
	mux.Handle("POST /settings/state-backups/inspect", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.inspectStateBackup)))
	mux.Handle("POST /settings/state-backups/stage", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.stageStateBackup)))
	mux.Handle("POST /settings/state-backups/stages/{id}/discard", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.discardStateBackupStage)))
	mux.Handle("GET /settings/updates/status", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.updateStatus)))
	mux.Handle("POST /settings/updates/check", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.checkUpdate)))
	mux.Handle("POST /settings/updates/prepare", a.requirePermission(identity.PermissionManageSystem, http.HandlerFunc(a.prepareUpdate)))
	mux.Handle("POST /settings/updates/apply", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.applyUpdate)))
	mux.Handle("POST /settings/updates/restart", a.requireStepUp(identity.PermissionManageSystem, http.HandlerFunc(a.restartService)))
	mux.Handle("GET /resources/databases", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.databasesPage)))
	mux.Handle("POST /resources/databases/redis/instances", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.saveRedisInstance)))
	mux.Handle("POST /resources/databases/redis/instances/{id}/test", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.testRedisInstance)))
	mux.Handle("POST /resources/databases/redis/instances/{id}/delete", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.deleteRedisInstance)))
	mux.Handle("POST /resources/databases/instances", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.saveMySQLInstance)))
	mux.Handle("POST /resources/databases/settings/backup-root", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.setMySQLBackupRoot)))
	mux.Handle("POST /resources/databases/settings/tools", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.setMySQLTools)))
	mux.Handle("POST /resources/databases/instances/{id}/test", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.testMySQLInstance)))
	mux.Handle("POST /resources/databases/instances/{id}/sql", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.executeMySQLReadOnlySQL)))
	mux.Handle("POST /resources/databases/instances/{id}/sql/write", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.executeMySQLWriteSQL)))
	mux.Handle("POST /resources/databases/instances/{id}/delete", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.deleteMySQLInstance)))
	mux.Handle("POST /resources/databases/instances/{id}/databases", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.createMySQLDatabase)))
	mux.Handle("POST /resources/databases/instances/{id}/backup", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.startMySQLBackup)))
	mux.Handle("POST /resources/databases/instances/{id}/backup/batch", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.startMySQLBatchBackup)))
	mux.Handle("POST /resources/databases/instances/{id}/drop", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.startDropMySQLDatabase)))
	mux.Handle("POST /resources/databases/instances/{id}/imports", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.importMySQLBackup)))
	mux.Handle("POST /resources/databases/instances/{id}/imports/server", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.importMySQLServerBackup)))
	mux.Handle("POST /resources/databases/instances/{id}/plans", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.saveMySQLPlan)))
	mux.Handle("POST /resources/databases/plans/{plan_id}", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.updateMySQLPlan)))
	mux.Handle("POST /resources/databases/plans/{plan_id}/delete", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.deleteMySQLPlan)))
	mux.Handle("GET /resources/databases/backups/{backup_id}/download", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.downloadMySQLBackup)))
	mux.Handle("POST /resources/databases/backups/{backup_id}/restore", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.startMySQLRestore)))
	mux.Handle("POST /resources/databases/backups/{backup_id}/delete", a.requireStepUp(identity.PermissionManageDatabases, http.HandlerFunc(a.deleteMySQLBackup)))
	mux.Handle("GET /resources/databases/operations/{operation_id}/status", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.mysqlOperationStatus)))
	mux.Handle("GET /resources/databases/operations/{operation_id}/events", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.mysqlOperationEvents)))
	mux.Handle("POST /resources/databases/operations/{operation_id}/cancel", a.requirePermission(identity.PermissionManageDatabases, http.HandlerFunc(a.cancelMySQLOperation)))
	mux.Handle("GET /resources/files/new-directory", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.newDirectoryTask)))
	mux.Handle("GET /resources/files/upload", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.uploadTask)))
	mux.Handle("GET /resources/files/move", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.moveFileTask)))
	mux.Handle("GET /resources/directories", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.hostDirectories)))
	mux.Handle("GET /resources/files/log", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileLogPage)))
	mux.Handle("GET /resources/files/log/download", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileLogDownload)))
	mux.Handle("GET /resources/files/log/history", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileLogHistory)))
	mux.Handle("GET /resources/files/log/events", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileLogEvents)))
	mux.Handle("GET /resources/files/run", a.requirePermission(identity.PermissionExecute, http.HandlerFunc(a.runFileTask)))
	mux.Handle("GET /resources/files/quick-run", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.quickRunFromFileTask)))
	mux.Handle("GET /resources/files", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.filesPage)))
	mux.Handle("GET /resources/files/validate", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.validateFileQuickAccess)))
	mux.Handle("GET /resources/files/quick-access", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileQuickAccessPins)))
	mux.Handle("POST /resources/files/quick-access", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.updateFileQuickAccessPin)))
	mux.Handle("POST /resources/files/mkdir", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.createDirectory)))
	mux.Handle("POST /resources/files/conflicts", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.uploadConflicts)))
	mux.Handle("POST /resources/files/upload", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.uploadFiles)))
	mux.Handle("POST /resources/files/upload-batch", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.uploadBatchFiles)))
	mux.Handle("GET /resources/files/download", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.downloadFile)))
	mux.Handle("GET /resources/files/preview", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.previewImage)))
	mux.Handle("GET /resources/files/view", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.previewTextPage)))
	mux.Handle("GET /resources/files/view/content", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.textPreviewContent)))
	mux.Handle("POST /resources/files/delete", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.deleteFile)))
	mux.Handle("POST /resources/files/move", a.requireStepUp(identity.PermissionWriteFiles, http.HandlerFunc(a.moveFile)))
	mux.Handle("POST /resources/files/toggle-executable", a.requireStepUp(identity.PermissionWriteFiles, http.HandlerFunc(a.toggleExecutable)))
	mux.Handle("GET /resources/files/operations/{id}", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileOperationPage)))
	mux.Handle("GET /resources/files/operations/{id}/status", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileOperationStatus)))
	mux.Handle("GET /resources/files/operations/{id}/events", a.requirePermission(identity.PermissionReadFiles, http.HandlerFunc(a.fileOperationEvents)))
	mux.Handle("POST /resources/files/operations/{id}/cancel", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.cancelFileOperation)))
	mux.Handle("GET /resources/trash", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.trashPage)))
	mux.Handle("GET /resources/inbox", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.uploadInboxPage)))
	mux.Handle("POST /resources/inbox/{id}/publish", a.requireStepUp(identity.PermissionWriteFiles, http.HandlerFunc(a.publishInboxUpload)))
	mux.Handle("POST /resources/inbox/{id}/discard", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.discardInboxUpload)))
	mux.Handle("POST /resources/trash/restore", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.restoreTrash)))
	mux.Handle("POST /resources/trash/purge", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.purgeTrash)))
	mux.Handle("POST /resources/trash/cleanup", a.requireStepUp(identity.PermissionWriteFiles, http.HandlerFunc(a.cleanupTrash)))
	mux.Handle("GET /resources/files/edit", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.editTextPage)))
	mux.Handle("POST /resources/files/edit", a.requirePermission(identity.PermissionWriteFiles, http.HandlerFunc(a.saveText)))
	mux.Handle("POST /history/runs/start", a.requirePermission(identity.PermissionExecute, http.HandlerFunc(a.startRun)))
	mux.Handle("GET /history/runs", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.runsPage)))
	mux.Handle("GET /history/runs/{id}/save-quick-run", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.saveQuickRunTask)))
	mux.Handle("GET /history/runs/{id}/source", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.runSource)))
	mux.Handle("GET /history/runs/{id}/download", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.downloadRun)))
	mux.Handle("GET /history/runs/{id}", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.runDetails)))
	mux.Handle("POST /history/runs/{id}/stop", a.requirePermission(identity.PermissionExecute, http.HandlerFunc(a.stopRun)))
	mux.Handle("GET /history/runs/{id}/history", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.runEventHistory)))
	mux.Handle("GET /history/runs/{id}/events", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.runEvents)))
	mux.Handle("GET /resources/variables", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.variablesPage)))
	mux.Handle("GET /resources/variables/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newVariableTask)))
	mux.Handle("GET /resources/variables/{name}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editVariableTask)))
	mux.Handle("POST /resources/variables", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createVariable)))
	mux.Handle("POST /resources/variables/{name}/update", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.updateVariable)))
	mux.Handle("POST /resources/variables/{name}/increment", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.incrementVariableVersion)))
	mux.Handle("POST /resources/variables/{name}/delete", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.deleteVariable)))
	mux.Handle("POST /history/runs/{id}/quick-run", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.saveQuickRun)))
	mux.Handle("GET /config/quick-runs", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.quickRunsPage)))
	mux.Handle("POST /config/quick-runs", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createQuickRunFromFile)))
	mux.Handle("GET /config/quick-runs/one-time/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.oneTimeRunTask)))
	mux.Handle("POST /config/quick-runs/one-time", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.startOneTimeRun)))
	mux.Handle("GET /config/quick-runs/from-source/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.quickCreateTask)))
	mux.Handle("POST /config/quick-runs/from-source", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createQuickRunFromSource)))
	mux.Handle("GET /config/quick-runs/groups/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newQuickRunGroupTask)))
	mux.Handle("POST /config/quick-runs/groups", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createQuickRunGroup)))
	mux.Handle("GET /config/quick-runs/groups/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editQuickRunGroupTask)))
	mux.Handle("POST /config/quick-runs/groups/{id}/update", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.updateQuickRunGroup)))
	mux.Handle("POST /config/quick-runs/groups/{id}/move-top", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.moveQuickRunGroupToTop)))
	mux.Handle("POST /config/quick-runs/groups/{id}/delete", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.deleteQuickRunGroup)))
	mux.Handle("POST /config/quick-runs/reorder", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.reorderQuickRuns)))
	mux.Handle("GET /config/quick-runs/{id}/move-group", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.moveQuickRunToGroupTask)))
	mux.Handle("POST /config/quick-runs/{id}/move-group", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.moveQuickRunToGroup)))
	mux.Handle("GET /config/quick-runs/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editQuickRunTask)))
	mux.Handle("POST /config/quick-runs/{id}/update", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.updateQuickRun)))
	mux.Handle("GET /config/quick-runs/{id}/copy", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.copyQuickRunTask)))
	mux.Handle("POST /config/quick-runs/{id}/copy", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.copyQuickRun)))
	mux.Handle("POST /config/quick-runs/{id}/lock", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.setQuickRunLocked)))
	mux.Handle("POST /config/quick-runs/{id}/start", a.requirePermission(identity.PermissionExecute, http.HandlerFunc(a.startQuickRun)))
	mux.Handle("POST /config/quick-runs/{id}/delete", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.deleteQuickRun)))
	mux.Handle("GET /config/schedules", a.requirePermission(identity.PermissionObserve, http.HandlerFunc(a.schedulesPage)))
	mux.Handle("GET /config/schedules/groups/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newScheduleGroupTask)))
	mux.Handle("POST /config/schedules/groups", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createScheduleGroup)))
	mux.Handle("GET /config/schedules/groups/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editScheduleGroupTask)))
	mux.Handle("POST /config/schedules/groups/{id}/update", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.updateScheduleGroup)))
	mux.Handle("POST /config/schedules/groups/{id}/move", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.moveScheduleGroup)))
	mux.Handle("POST /config/schedules/groups/{id}/delete", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.deleteScheduleGroup)))
	mux.Handle("GET /config/schedules/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newScheduleTask)))
	mux.Handle("GET /config/schedules/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editScheduleTask)))
	mux.Handle("POST /config/schedules/preview", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.previewScheduleCron)))
	mux.Handle("POST /config/schedules/{id}/preview", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.previewScheduleCron)))
	mux.Handle("POST /config/schedules", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.createSchedule)))
	mux.Handle("POST /config/schedules/{id}/update", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.updateSchedule)))
	mux.Handle("POST /config/schedules/{id}/toggle", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.toggleSchedule)))
	mux.Handle("POST /config/schedules/{id}/run", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.runScheduleNow)))
	mux.Handle("POST /config/schedules/{id}/delete", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.deleteSchedule)))
	mux.Handle("GET /config/external-interfaces", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.externalInterfacesPage)))
	mux.Handle("GET /config/external-interfaces/control", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.externalGlobalControlTask)))
	mux.Handle("POST /config/external-interfaces/control", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.setExternalGlobalControl)))
	mux.Handle("GET /config/external-interfaces/groups/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newExternalGroupTask)))
	mux.Handle("POST /config/external-interfaces/groups", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.createExternalGroup)))
	mux.Handle("GET /config/external-interfaces/groups/{groupID}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editExternalGroupTask)))
	mux.Handle("POST /config/external-interfaces/groups/{groupID}", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.updateExternalGroup)))
	mux.Handle("GET /config/external-interfaces/groups/{groupID}/keys/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newExternalKeyTask)))
	mux.Handle("GET /config/external-interfaces/keys/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newExternalKeyTask)))
	mux.Handle("POST /config/external-interfaces/groups/{groupID}/keys", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.createExternalKey)))
	mux.Handle("POST /config/external-interfaces/keys", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.createExternalKey)))
	mux.Handle("GET /config/external-interfaces/keys/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editExternalKeyTask)))
	mux.Handle("GET /config/external-interfaces/keys/{id}/rotate", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.rotateExternalKeyTask)))
	mux.Handle("POST /config/external-interfaces/keys/{id}", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.updateExternalKey)))
	mux.Handle("POST /config/external-interfaces/keys/{id}/toggle", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.toggleExternalKey)))
	mux.Handle("POST /config/external-interfaces/keys/{id}/rotate", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.rotateExternalKey)))
	mux.Handle("POST /config/external-interfaces/keys/{id}/delete", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.deleteExternalKey)))
	mux.Handle("GET /config/external-interfaces/groups/{groupID}/entries/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newExternalEntryTask)))
	mux.Handle("POST /config/external-interfaces/groups/{groupID}/entries", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.createExternalEntry)))
	mux.Handle("GET /config/external-interfaces/keys/{id}/entries/new", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.newExternalEntryTask)))
	mux.Handle("POST /config/external-interfaces/keys/{id}/entries", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.createExternalEntry)))
	mux.Handle("GET /config/external-interfaces/entries/{id}", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.externalEntryDetail)))
	mux.Handle("GET /config/external-interfaces/entries/{id}/edit", a.requirePermission(identity.PermissionManageExecution, http.HandlerFunc(a.editExternalEntryTask)))
	mux.Handle("POST /config/external-interfaces/entries/{id}", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.updateExternalEntry)))
	mux.Handle("POST /config/external-interfaces/entries/{id}/toggle", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.toggleExternalEntry)))
	mux.Handle("POST /config/external-interfaces/entries/{id}/delete", a.requireStepUp(identity.PermissionManageExecution, http.HandlerFunc(a.deleteExternalEntry)))
	mux.Handle("GET /history/audit", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(a.auditPage)))
	mux.Handle("GET /history/audit.csv", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(a.auditDownload)))
	mux.Handle("GET /history/audit/service-logs", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(a.serviceLogsPage)))
	mux.Handle("GET /history/audit/service-logs.csv", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(a.exportServiceLogs)))
	mux.Handle("GET /history/audit/service-logs.txt", a.requirePermission(identity.PermissionReadAudit, http.HandlerFunc(a.exportServiceLogsText)))
	a.routeSpecs = mux.Specs()
	return http.HandlerFunc(func(response http.ResponseWriter, request *http.Request) {
		requestID, err := randomToken(18)
		if err != nil {
			http.Error(response, "unable to create request correlation", http.StatusInternalServerError)
			return
		}
		request = request.WithContext(context.WithValue(request.Context(), requestIDContextKey, requestID))
		response.Header().Set("X-Request-ID", requestID)
		if !validRequestTarget(request) {
			http.Error(response, "ambiguous request target", http.StatusBadRequest)
			return
		}
		request, err = a.applyTrustedProxy(request)
		if err != nil {
			http.Error(response, "invalid trusted proxy headers", http.StatusBadRequest)
			return
		}
		if !a.validRequestHost(request.Host) {
			http.Error(response, "request host is not allowed", http.StatusMisdirectedRequest)
			return
		}
		response.Header().Set("X-Content-Type-Options", "nosniff")
		response.Header().Set("X-Frame-Options", "DENY")
		// Keep same-origin form submissions bound to a concrete Origin. Chromium
		// serializes the Origin as "null" for native POST forms under no-referrer,
		// which makes strict same-origin validation indistinguishable from an
		// opaque, potentially hostile origin.
		response.Header().Set("Referrer-Policy", "same-origin")
		response.Header().Set("Permissions-Policy", "camera=(), geolocation=(), microphone=()")
		response.Header().Set("Content-Security-Policy", "default-src 'self'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'")
		if isSecureRequest(request) {
			response.Header().Set("Strict-Transport-Security", "max-age=31536000")
		}
		isExternalTrigger := request.URL.Path == "/trigger" || strings.HasPrefix(request.URL.Path, "/trigger/")
		if a.validation.Load() && (request.Method != http.MethodGet || isExternalTrigger) {
			response.Header().Set("Retry-After", "2")
			if isExternalTrigger {
				response.Header().Set("Content-Type", "application/json; charset=utf-8")
				writeExternalTriggerError(response, http.StatusServiceUnavailable, "service_unavailable")
			} else {
				http.Error(response, webText(resolveWebLocale(request), "updates.validation_write_blocked"), http.StatusServiceUnavailable)
			}
			return
		}
		pageResponse := &pageResponseWriter{ResponseWriter: response}
		mux.ServeHTTP(pageResponse, request)
		pageResponse.finish(a, request)
		if pageResponse.status == http.StatusMethodNotAllowed {
			auditRequest := request
			if current, _, ok := a.loadSession(request); ok {
				auditRequest = request.WithContext(context.WithValue(request.Context(), sessionContextKey, current))
				a.recordAuditForRequest(auditRequest, "unknown_method", request.Method+" "+request.URL.Path, "blocked")
			} else {
				a.recordAuditWithRequestActor(auditRequest, "unknown_method", request.Method+" "+request.URL.Path, "blocked", request.RemoteAddr, "", "", "")
			}
		}
	})
}
