const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = async function fileJumpTest(page, baseURL, hostRoot, screenshotRoot) {
  page.setDefaultTimeout(10000);
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const root=path.join(hostRoot,'jump-fixtures'),child=path.join(root,'中文 & nested');
  fs.mkdirSync(child,{recursive:true});
  for(let i=0;i<45;i++)fs.writeFileSync(path.join(root,`entry-${String(i).padStart(2,'0')}.txt`),'fixture');
  fs.writeFileSync(path.join(child,'nested-match.txt'),'nested');
  fs.writeFileSync(path.join(root,'.hidden-match.txt'),'hidden');
  const url=baseURL+'/resources/files?'+new URLSearchParams({path:root,sort:'name'});
  const open=async()=>{await page.locator('[data-file-jump-open]').click();await page.locator('.file-jump-dialog').waitFor({state:'visible'});};
  const search=async()=>{await page.locator('[data-jump-tab="search"]').click();};
  const query=()=>page.locator('#jump-query');
  await page.goto(url);await open();
  assert.equal(await page.locator('#jump-path').inputValue(),root);
  assert.equal(await page.locator('#jump-path').evaluate(n=>n===document.activeElement),true);
  if(screenshotRoot){fs.mkdirSync(screenshotRoot,{recursive:true});await page.screenshot({path:path.join(screenshotRoot,'file-jump-address.png')});}
  await page.locator('#jump-path').fill('missing-file');await page.locator('#jump-path').press('Enter');
  await page.locator('#jump-address-status').filter({hasText:'no longer exists'}).waitFor();
  assert.equal(await page.locator('#jump-path').inputValue(),'missing-file');
  await search();assert.match(await page.locator('#jump-search-status').textContent(),/Enter a file/);
  await query().fill('nested-match');await page.locator('[data-jump-result]').waitFor();
  assert.match(await page.locator('[data-jump-result]').textContent(),/中文 & nested/);
  await page.locator('[data-jump-tab="address"]').click();assert.equal(await page.locator('#jump-path').inputValue(),'missing-file');
  await search();assert.equal(await query().inputValue(),'nested-match');
  await page.locator('select[name=scope]').selectOption('current');await page.locator('#jump-search-status').filter({hasText:'No matches'}).waitFor();
  assert.equal(await page.locator('[data-jump-result]').count(),0);
  await page.locator('select[name=scope]').selectOption('recursive');await page.locator('[data-jump-result]').waitFor();
  fs.writeFileSync(path.join(hostRoot,'all-scope-match.txt'),'outside current directory');
  await query().fill('all-scope-match');await page.locator('#jump-search-status').filter({hasText:'No matches'}).waitFor();
  await page.locator('select[name=scope]').selectOption('all');await page.locator('[data-jump-result]').filter({hasText:'all-scope-match'}).waitFor();
  assert.equal(await page.locator('[data-jump-all-hint]').isVisible(),true);
  if(screenshotRoot)await page.screenshot({path:path.join(screenshotRoot,'file-jump-all.png')});
  await page.locator('[data-jump-result]').click();await page.waitForURL(u=>u.searchParams.get('focus_path')===path.join(hostRoot,'all-scope-match.txt'));await page.locator('[data-file-focus]').waitFor();
  await page.goto(url);await open();await search();await query().fill('nested-match');await page.locator('[data-jump-result]').waitFor();

  await query().press('ArrowDown');assert.equal(await page.locator('[data-jump-result]').evaluate(n=>n===document.activeElement),true);
  await page.keyboard.press('Enter');await page.waitForURL(u=>u.searchParams.get('focus_path')===path.join(child,'nested-match.txt'));
  await page.locator('[data-file-focus]').waitFor();assert.equal(await page.locator('.file-jump-dialog').count(),0);
  await page.goBack();await page.locator('[data-file-jump-open]').waitFor();assert.equal(new URL(page.url()).searchParams.get('path'),root);
  await open();await page.locator('#jump-path').fill('./entry-44.txt');await page.locator('#jump-path').press('Enter');
  await page.waitForURL(u=>u.searchParams.get('focus_path')===path.join(root,'entry-44.txt'));await page.locator('[data-file-focus]').waitFor();
  assert.match(await page.locator('.pagination').textContent(),/3 \/ 3/);
  assert.equal(new URL(page.url()).searchParams.get('page'),'3');
  assert.equal(await page.locator('[data-file-focus]').getAttribute('data-file-path'),path.join(root,'entry-44.txt'));
  await open();await page.locator('#jump-path').fill(path.join(root,'.hidden-match.txt'));await page.locator('#jump-path').press('Enter');
  await page.waitForURL(u=>u.searchParams.get('show_hidden')==='1');await page.locator('[data-file-focus]').waitFor();
  assert.equal(await page.locator('[data-file-focus]').getAttribute('data-file-path'),path.join(root,'.hidden-match.txt'));
  // Legacy location links used by Quick access and Documents also normalize the page.
  await page.goto(baseURL+'/resources/files?'+new URLSearchParams({path:root,focus_path:path.join(root,'entry-44.txt'),page:'1',q:'entry-00',sort:'name'}));
  await page.locator('[data-file-focus]').waitFor();assert.equal(new URL(page.url()).searchParams.get('page'),'3');assert.equal(new URL(page.url()).searchParams.has('q'),false);
  await page.goto(url);await open();await search();
  let releaseOld; const gate=new Promise(resolve=>releaseOld=resolve);
  await page.route('**/resources/files/jump?**',async route=>{const u=new URL(route.request().url());if(u.searchParams.get('q')==='entry-0'&&u.searchParams.get('format')==='json'){await gate;await route.fulfill({contentType:'application/json',body:JSON.stringify({Entries:[],Partial:false})}).catch(()=>{});}else await route.continue();});
  const old=page.waitForRequest(r=>new URL(r.url()).searchParams.get('q')==='entry-0');await query().fill('entry-0');await old;
  await query().fill('entry-44');await page.locator('[data-jump-result]').filter({hasText:'entry-44'}).waitFor();releaseOld();
  assert.equal(await page.locator('[data-jump-result]').count(),1);
  await page.unroute('**/resources/files/jump?**');
  if(screenshotRoot)await page.screenshot({path:path.join(screenshotRoot,'file-jump-search.png')});
  await page.keyboard.press('Escape');await page.locator('.file-jump-dialog').waitFor({state:'detached'});
  assert.equal(await page.locator('[data-file-jump-open]').evaluate(n=>n===document.activeElement),true);
  // An IME composition must not start a search until the text is committed.
  await open();await search();let compositionRequests=0;
  const countComposition=request=>{if(new URL(request.url()).searchParams.get('q')==='entry-43')compositionRequests++;};page.on('request',countComposition);
  await query().dispatchEvent('compositionstart');await query().fill('entry-43');
  await query().press('Enter');assert.equal(compositionRequests,0);
  await query().dispatchEvent('compositionend');await page.locator('[data-jump-result]').filter({hasText:'entry-43'}).waitFor();
  page.off('request',countComposition);assert.equal(compositionRequests,1);await page.keyboard.press('Escape');
  // Closing while the destination page is loading must prevent a late navigation.
  await open();await page.locator('#jump-path').fill('./entry-42.txt');
  let releaseNavigation;const navigationGate=new Promise(resolve=>releaseNavigation=resolve);
  await page.route('**/resources/files?**',async route=>{if(new URL(route.request().url()).searchParams.get('focus_path')===path.join(root,'entry-42.txt')){await navigationGate;await route.continue().catch(()=>{});}else await route.continue();});
  const loading=page.waitForRequest(request=>new URL(request.url()).pathname==='/resources/files'&&new URL(request.url()).searchParams.get('focus_path')===path.join(root,'entry-42.txt'));
  const cancelled=page.waitForEvent('requestfailed',{predicate:request=>new URL(request.url()).searchParams.get('focus_path')===path.join(root,'entry-42.txt')});
  await page.locator('#jump-path').press('Enter');await loading;await page.keyboard.press('Escape');releaseNavigation();await cancelled;
  await page.unroute('**/resources/files?**');assert.equal(page.url(),url);assert.equal(await page.locator('.file-jump-dialog').count(),0);
  await page.setViewportSize({width:390,height:844});await open();await search();await query().fill('entry');await page.locator('[data-jump-result]').first().waitFor();
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  assert.equal(await page.locator('.file-jump-dialog').evaluate(n=>{const r=n.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}),true);
  if(screenshotRoot)await page.screenshot({path:path.join(screenshotRoot,'file-jump-mobile.png')});
  await page.keyboard.press('Escape');await page.setViewportSize({width:1440,height:1000});
  const context=await page.context().browser().newContext({javaScriptEnabled:false,locale:'en-US',reducedMotion:'reduce'});
  const fallback=await context.newPage();await fallback.bringToFront();fallback.setDefaultTimeout(30000);
  await fallback.goto(baseURL+'/login');await fallback.locator('[name=username]').fill('admin');await fallback.locator('[name=password]').fill('calibration-ledger-2026');await fallback.locator('[data-login-form] button[type=submit]').click();await fallback.waitForURL('**/monitor');
  await fallback.goto(url);await fallback.locator('[data-file-jump-open]').click({noWaitAfter:true});
  await fallback.waitForURL('**/resources/files/jump?**',{waitUntil:'domcontentloaded'});
  await fallback.locator('[data-jump-tab=search]').click();await fallback.locator('#jump-query').fill('nested-match');await fallback.locator('[data-jump-form=search] button').click();
  await fallback.locator('[data-jump-result]').click();await fallback.locator('[data-file-focus]').waitFor();
  assert.equal(await fallback.locator('[data-file-focus]').getAttribute('data-file-path'),path.join(child,'nested-match.txt'));await context.close();
  assert.deepEqual(errors,[]);return {root,checks:24};
};
