const assert = require('node:assert/strict');
module.exports = async function verifyWorkbench(page, baseURL, screenshots) {
  const boardName='Workbench acceptance '+Date.now();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.addInitScript(()=>{Object.defineProperty(Crypto.prototype,'randomUUID',{value:undefined,configurable:true});});
  await page.goto(baseURL + '/resources/workbench');
  await page.locator('.wb-enhanced').waitFor();
  const root=page.locator('[data-workbench]');
  const save=()=>page.locator('.wb-status').filter({hasText:/已保存|Saved/}).waitFor();
  await root.getByRole('button',{name:/^(编辑|Edit)$/}).click();
  await root.getByRole('button',{name:/^(新建面板|New board)$/}).click();
  await root.getByRole('textbox',{name:/^(面板名称|Board name)$/}).fill(boardName);
  for(const kind of ['note','todo','timer','links','draw']) await root.locator('[data-add="'+kind+'"]').click();
  await root.locator('.wb-note textarea').last().fill('A saved note <script>literal</script>');
  const todo=root.locator('.wb-todo').last();
  await todo.getByRole('textbox',{name:/^(添加待办|Add task)$/}).fill('Initial task');
  await todo.getByRole('textbox',{name:/^(添加待办|Add task)$/}).press('Enter');
  await todo.getByRole('textbox',{name:/^(待办内容|Task text)$/}).fill('Edited task');
  await todo.getByRole('checkbox').check();
  const links=root.locator('.wb-links').last();
  await links.getByRole('textbox',{name:/^(收藏链接|Save URL)$/}).fill('http://example.com');
  await links.getByRole('textbox',{name:/^(收藏链接|Save URL)$/}).press('Enter');
  await links.getByRole('button',{name:/^(编辑此链接|Edit link)$/}).click();
  await links.getByRole('textbox',{name:/^(链接标题|Link title)$/}).fill('Edited reference');
  await links.getByRole('textbox',{name:/^(链接地址|Link URL)$/}).fill('https://example.com/edited');
  await links.getByRole('button',{name:/^(保存链接|Save link)$/}).click();
  await root.locator('.wb-timer').last().getByRole('button',{name:/^(开始|Start)$/}).click();
  await page.waitForTimeout(1200);
  assert.notEqual(await root.locator('.wb-digits').last().textContent(),'25:00');
  await root.locator('.wb-timer').last().getByRole('button',{name:/^(暂停|Pause)$/}).click();
  const drawing=root.locator('.wb-draw').last();
  await drawing.locator('[data-size=xlarge]').click();
  await page.waitForTimeout(100);
  const canvas=drawing.locator('canvas');let r=await canvas.boundingBox();
  await page.mouse.move(r.x+60,r.y+60);await page.mouse.down();await page.mouse.move(r.x+100,r.y+85,{steps:8});await page.mouse.up();await save();
  const read=async()=>{const response=await page.request.get(baseURL+'/resources/workbench/state');assert.equal(response.status(),200);return response.json();};
  const getDrawing=s=>s.boards.find(b=>b.name===boardName).items.find(w=>w.type==='draw');
  const prior=getDrawing(await read()).strokes;assert(prior[0].points.length>1);
  await drawing.locator('[data-size=small]').click();await drawing.locator('[data-size=xlarge]').click();
  await drawing.getByRole('button',{name:/^(移动画布|Move canvas)$/}).click();
  r=await canvas.boundingBox();await page.mouse.move(r.x+60,r.y+60);await page.mouse.down();await page.mouse.move(r.x+140,r.y+100,{steps:6});await page.mouse.up();await save();
  const after=getDrawing(await read());assert.deepEqual(after.strokes,prior);assert.equal(after.pan.x,80);assert.equal(after.pan.y,40);
  const sc=await root.locator('.wb-scroll').boundingBox(),card=await drawing.boundingBox();assert(card.y>=sc.y-1&&card.y+card.height<=sc.y+sc.height+1);
  const tabBefore=await root.locator('.wb-boardbar').boundingBox();await root.locator('.wb-scroll').evaluate(e=>e.scrollTop=0);assert.deepEqual(await root.locator('.wb-boardbar').boundingBox(),tabBefore);assert.equal(await page.evaluate(()=>scrollY),0);
  await root.getByRole('button',{name:/^(查看|View)$/}).click();assert(await root.locator('.wb-note textarea').last().evaluate(e=>e.readOnly));assert(!await root.locator('[data-add=note]').isVisible());assert(await root.locator('.wb-dock').isVisible());
  await save();await page.reload();await page.locator('.wb-enhanced').waitFor();await root.locator('.wb-tabs').getByRole('button',{name:boardName,exact:true}).click();assert.equal(await root.locator('.wb-note textarea').inputValue(),'A saved note <script>literal</script>');assert(await root.getByText('Edited task',{exact:true}).isVisible());assert.equal(await root.getByRole('link',{name:/Edited reference/}).getAttribute('href'),'https://example.com/edited');
  await root.getByRole('button',{name:/^(编辑|Edit)$/}).click();await root.locator('.wb-draw [data-size=medium]').click();await save();
  if(screenshots)await page.screenshot({path:screenshots+'/workbench-desktop.png'});
  await page.setViewportSize({width:390,height:844});await root.locator('.wb-draw [data-size=xlarge]').click();await page.waitForTimeout(100);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const mobileCard=await root.locator('.wb-draw').boundingBox(),mobileScroll=await root.locator('.wb-scroll').boundingBox();assert(mobileCard.y>=mobileScroll.y-1&&mobileCard.y+mobileCard.height<=mobileScroll.y+mobileScroll.height+1);if(screenshots)await page.screenshot({path:screenshots+'/workbench-mobile.png'});await save();
  await page.setViewportSize({width:1440,height:1000});
  await root.locator('.wb-timer select').selectOption('0');await save();await page.reload();await page.locator('.wb-enhanced').waitFor();await root.locator('.wb-tabs').getByRole('button',{name:boardName,exact:true}).click();assert.equal(await root.locator('.wb-digits').textContent(),'00:00');
  await page.goto(baseURL+'/monitor');await page.locator('a[href="/resources/workbench"]').click();await page.locator('.wb-enhanced').waitFor();await root.locator('.wb-tabs').getByRole('button',{name:boardName,exact:true}).click();await root.getByRole('button',{name:/^(编辑|Edit)$/}).click();await root.locator('.wb-note textarea').fill('Saved before browser Back');await page.goBack();await page.waitForURL('**/monitor');await page.locator('[data-workbench]').waitFor({state:'detached'});assert.equal((await read()).boards.find(b=>b.name===boardName).items.find(w=>w.type==='note').text,'Saved before browser Back');
  await page.locator('a[href="/resources/workbench"]').click();await page.locator('.wb-enhanced').waitFor();await root.locator('.wb-tabs').getByRole('button',{name:boardName,exact:true}).click();await root.getByRole('button',{name:/^(编辑|Edit)$/}).click();
  // A stale revision cannot overwrite changes from a second browser session.
  const data=await read();const csrf=await root.getAttribute('data-csrf');let response=await page.request.post(baseURL+'/resources/workbench/state',{data,headers:{'X-CSRF-Token':csrf}});assert.equal(response.status(),200);response=await page.request.post(baseURL+'/resources/workbench/state',{data,headers:{'X-CSRF-Token':csrf}});assert.equal(response.status(),409);
  await root.locator('.wb-note textarea').fill('Unsent conflict text');await root.locator('.wb-status').filter({hasText:/另一个窗口|Another window/}).waitFor();assert.equal(await root.locator('.wb-note textarea').inputValue(),'Unsent conflict text');
  assert.deepEqual(errors,[]);
  page.once('dialog',d=>d.accept());await page.reload();await page.locator('.wb-enhanced').waitFor();
};
